[workspace]
members = [
    "modules/traits",
    "modules/signal",
    "modules/scheduler",
    "modules/tax",
    "modules/committee",
    "modules/haggle",
    "modules/vote",
    # runtimes
    "runtimes/main",
    "runtimes/genesis",
]